### ISSUE TITLE
Keeping flakes pure with home-manager and sops

### ISSUE THREAD

**Issue by collinarnett** [Mic92/sops-nix#154]
Hello,

I'm using home-manager, flakes and sops and I've integrated sops into my configuration file like so:
```nix
{ nixosConfig, ...}:
{
  programs.awscli2 = {
    enable = true;
    config = nixosConfig.sops.secrets.awscli2-config.path;
    credentials = nixosConfig.sops.secrets.awscli2-credentials.path;
  };
}
```
however, this results in:
```
error: access to absolute path '/run/secrets/awscli2-config' is forbidden in pure eval mode (use '--impure' to override
```

This does not occur when using sops secrets outside of home-manager, in my case inside `configuration.nix`.

Is this unavoidable when using flakes or am I doing something wrong?

**Comment by colemickens** [comment]
Where's the source for the module you're configuring? I don't see such a `programs.awscli2` module in `nixpkgs` or `home-manager`?

**Comment by collinarnett** [comment]
I wrote this very simple module and I just include it in my `home.nix`
```nix 
{ config, lib, pkgs, ... }:

with lib;

let cfg = config.programs.awscli2;
in {

  options.programs.awscli2 = with lib.types; {
    enable = mkEnableOption "Awscli2";

    config = mkOption {
      type = nullOr path;
      default = null;
    };

    credentials = mkOption {
      type = nullOr path;
      default = null;
    };

  };

  config = mkIf cfg.enable {
    home.packages = [ pkgs.awscli2 ];

    xdg.configFile."awscli2/config" =
      mkIf (cfg.config != null) { source = cfg.config; };

    xdg.configFile."awscli2/credentials" =
      mkIf (cfg.config != null) { source = cfg.credentials; };
  };
}
```

**Comment by Mic92** [comment]
seems like this module tries to add the secret to the nix store path rather than treating it as a string.

**Comment by Mic92** [comment]
So xdg.configFile.<name>.source has the `path` type: https://github.com/nix-community/home-manager/blob/5209ea0d8c77399ec4987590e9738953f15f8d80/modules/lib/file-type.nix#L42

So nix is trying to convert your `nixosConfig.sops.secrets.awscli2-config.path` to a path, which might fail?

**Comment by Mic92** [comment]
Maybe you can ask in the home-manager repo if it was acceptable to also allow creation of symlinks to non-nix store paths.
Otherwise you can probably symlink yourself in some activation script or so.

**Comment by collinarnett** [comment]
I think rather than writing a home-manager module it's simpler in my use case to specify the location of the credentials file and config file using environment variables:
```
AWS_SHARED_CREDENTIALS_FILE
AWS_CONFIG_FILE
```

**Comment by bandithedoge** [comment]
You can fix this with [`mkOutOfStoreSymlink`](https://github.com/nix-community/home-manager/blob/12e26a74e5eb1a31e13daaa08858689e25ebd449/modules/files.nix#L64-L69).

**Comment by brokenpip3** [comment]
> You can fix this with [`mkOutOfStoreSymlink`](https://github.com/nix-community/home-manager/blob/12e26a74e5eb1a31e13daaa08858689e25ebd449/modules/files.nix#L64-L69).

hei @bandithedoge thanks for the hint! I have the same problem of OP, can you give me a short example on what you mean?

**Comment by sabitm** [comment]
Example use of `mkOutOfStoreSymlink` to fix this. `xdg.configFile.<name>.source` expect a path (not string) and we work around that using `mkOutOfStoreSymlink`(CMIIW).

```nix
{ config, lib, ... }:
let
  confSecret = config.sops.secrets.rclone.path;
  confSource = config.lib.file.mkOutOfStoreSymlink confSecret;
in 
{
  # Enable rclone
  programs.rclone.enable = true;

  # Config file
  xdg.configFile."rclone/rclone.conf" = {
    source = confSource;
  };
}
```
