### ISSUE TITLE
Passphrase protecting age keys

### ISSUE THREAD

**Issue by GrafBlutwurst** [Mic92/sops-nix#160]
I was wondering if it was possible to design a workaround that allows to have age keys be passphrase protected at rest? 
It seems that sops does not support this out of the box (see https://github.com/mozilla/sops/issues/933 or at least i could not find anything).

Maybe it would be possible to passphrase encrypt the age key on disk and then have a nix shell derivation as part of the flake that prompts the user for the passphrase and makes the key temporarily availble to sops in an unprotected fashion. Perhaps it would be possible to do this by using sops own `exec-env` or `exec-file`?

**Comment by Mic92** [comment]
Would gnupg keys not be a better fit for you usecase?

**Comment by Mic92** [comment]
I think age itself also supports password protected ssh keys? Maybe you can use age to decrypt another age key that is passed to sops. I have no plans on having support for this in sops-nix itself, but I would link to tutorials allowing this.

**Comment by dasJ** [comment]
We have something that might be helpful when you try to hack this together:
```bash
#!/usr/bin/env bash
set -euo pipefail

if [ -n "${VISOPS_PIPE:-}" ]; then
	declare SOPS_AGE_KEY_FILE
	SOPS_AGE_KEY_FILE="$(mktemp -p /dev/shm)"
	export SOPS_AGE_KEY_FILE
	trap 'rm -f "${SOPS_AGE_KEY_FILE}"' INT TERM EXIT
	eval "${VISOPS_PIPE}" > "${SOPS_AGE_KEY_FILE}"
fi
sops "${@}"
```

Essentially this allow you to do something like:
```bash
export VISOPS_PIPE='pass whatever/key | ssh-to-age -private-key'
$THE_SCRIPT_FROM_ABOVE -d myfile.yml
```

**Comment by Mic92** [comment]
Yeah something like should solve your issue.

**Comment by Mic92** [comment]
You can also replace it with your favorite password manager
