### ISSUE TITLE
Confusing need of using `sops.secrets.foo = { };` prior accessing it

### ISSUE THREAD

**Issue by otavio** [Mic92/sops-nix#173]
First, I'd like to thank you for maintaining this. It is very useful.

I struggled to get this working to figure out I had to force the evaluation of secret before accessing it. Is this intended?

**Comment by Mic92** [comment]
Yes this indented. Only secrets that are defined in the nixos module actually gets decrypted to the filesystem. This way you don't have decrypted secrets that are not used.
