### ISSUE TITLE
Usage without sudo

### ISSUE THREAD

**Issue by qbit** [Mic92/sops-nix#174]
It seems something is requiring `sudo`. If one sets:

```
config = {
    security = {
      doas = {
        enable = true;
        extraRules = [{
          groups = [ "wheel" ];
          persist = true;
        }];

      };
      sudo.enable = false;
    };
};
```

running `nixos-rebuild switch` will error saying it can't find sudo:

```
root@europa[1]:~qbit/src/nix-conf# nixos-rebuild --flake .#box switch --impure --build-host localhost --target-host root@box
building the system configuration...
copying 0 paths...
zsh:1: command not found: sudo
root@europa[127]:~qbit/src/nix-conf# 
```
I tried poking through the source for `sudo` but I don't see anything that is explicitly calling it.

**Comment by dasJ** [comment]
Are you in a `sudo -s` session? Or to be more precise, is `$SUDO_USER` set?

**Comment by qbit** [comment]
Ah, that was it! Thanks!

**Comment by dasJ** [comment]
For future reference, this is the code calling sudo, coming from `nixos-rebuild`: https://github.com/NixOS/nixpkgs/blob/204366af6ddce48b873ad5b293fc61285e29a065/pkgs/os-specific/linux/nixos-rebuild/nixos-rebuild.sh#L146,L148

**Comment by qbit** [comment]
Good to know! Thank you!
