### ISSUE TITLE
Relative sopsPGPKeyDir fails with `nix develop` from subdirectory

### ISSUE THREAD

**Issue by robx** [Mic92/sops-nix#175]
I'm working on a project with `/project/flake.nix` and `sops-nix`, with a `mkShell { sopsPGPKeyDir = "./secrets/keys" }`.

Then the following works as expected:

```
$ cd /project
$ nix develop
[nix-develop]$ 
```

But this doesn't:

```
$ cd /project/src
$ nix develop
path '/project/src' does not contain a 'flake.nix', searching up
find: ‘./secrets/keys’: No such file or directory
```

I'm finding it hard to say if this is due to an issue with the sops-nix config, or if nix's "searching up" functionality is broken (whether by design or implementation). Any insight appreciated!

**Comment by Mic92** [comment]
How about this?

```
mkShell { sopsPGPKeyDir = "${toString ./.}/secrets/keys"; }
```

**Comment by robx** [comment]
> How about this?
> 
> ```
> mkShell { sopsPGPKeyDir = "${toString ./.}/secrets/keys"; }
> ```

That works, thanks!

Would it make sense to prepend `./.` automatically, or is this just something that users should do?

**Comment by Mic92** [comment]
There might be case where one wants absolute directories... I just improved the documentation instead: https://github.com/Mic92/sops-nix/pull/176/commits/d27137c0a1daa745d45ee2c1886cafbc5afef04c
