### ISSUE TITLE
path attribute is wrong when using slashes in names

### ISSUE THREAD

**Issue by SuperSandro2000** [Mic92/sops-nix#182]
I am accessing the following secret ``config.sops.secrets."a/b".path`` which gets places in ``/run/secrets/a-b`` but path returns ``/run/secrets/a/b``.

**Comment by dasJ** [comment]
Do you set anything else on the secret? Because I use this pretty much every day and it works for me (the secret is in `/run/secrets/a/b`). Is there a `/run/secrets/a` **file** already so you cannot create the directory?

**Comment by SuperSandro2000** [comment]
> Is there a `/run/secrets/a` **file** already so it cannot create the directory?

I am not sure but that could have been the case while testing.

I just doubled checked and the error is no longer happening and I am not setting the path for everything. Going to close this for now.
