### ISSUE TITLE
Override flake inputs for older releases instead of having 3 nixpkgs

### ISSUE THREAD

**Issue by SuperSandro2000** [Mic92/sops-nix#187]
Right now if you use sops-nix as a flake without follows you get a total of 3 different nixpkgs added to your flake. Wouldn't it be easier to overwrite the nixpkgs input in the CI instead?

**Comment by Mic92** [comment]
Are those not loaded lazy or am I missing something?

**Comment by Mic92** [comment]
Otherwise I can see if I can hide it somehow.

**Comment by SuperSandro2000** [comment]
> Are those not loaded lazy or am I missing something?

Yeah, right. I thought they where downloaded when doing ``nix flake update`` but on a second check that does not seem to be the case.

**Comment by Mic92** [comment]
Ok. I am assuming this is not an issue for users than. We will also drop the current nixos release soonish.
