### ISSUE TITLE
Provide releases so we are able to pin a version of "sops-nix" in the configuration files

### ISSUE THREAD

**Issue by a1994sc** [Mic92/sops-nix#192]
I have the following configuration file called `sops.nix` 

```
{ config, pkgs, lib, ... }:

{
  imports = [ "${builtins.fetchTarball "https://github.com/Mic92/sops-nix/archive/master.tar.gz"}/modules/sops" ];

  environment.systemPackages = with pkgs; [
    age
    gnupg
  ];
}
```

It fetches the most recent commits from your repo which is for the most part fine... but as I am using this on a RPi the compile time for your code takes a while... So it would be nice to specify something like `version-1.5` or something like that so it can stay consistent.

I am newer to nixos so there maybe a disconnect that I am missing. Thank you.

**Comment by A1994SC** [comment]
For reference, the current build time on my RPi 4B was `31 minutes 29 seconds`

**Comment by SuperSandro2000** [comment]
I would suggest to use another fetcher which allows setting rev like fetchFromGitHub and pin it to a for you cached version.

**Comment by A1994SC** [comment]
I have tried to use fetchFromGitHub before and have ran into issues.... but I can try to see if I can figure it out, thanks

**Comment by Mic92** [comment]
What about?

```
builtins.fetchTarball "https://github.com/Mic92/sops-nix/archive/25ae48cbf2e91b1ea96afaea1dbd6ab50b3e1460.tar.gz"
```

**Comment by a1994sc** [comment]
This was fixed by using flakes
