### ISSUE TITLE
How do you use the sops module with niv?

### ISSUE THREAD

**Issue by antifuchs** [Mic92/sops-nix#20]
Hi again, I'm getting so close to being able to use sops-nix to keep secrets on my host (Thanks for the fixing those last two  issues so quickly)! - unfortunately, my luck has run out as I'm pulling sops-nix in with `niv`, and I don't understand how importing a sub-module of a niv-managed package should work. Using `imports = [ <sops-nix/modules/sops> ];` in my nix files fails with `error: file 'sops-nix/modules/sops' was not found in the Nix search path (add it using $NIX_PATH or -I), at /Users/asf/Mess/current/sops-sobs/configuration.nix:3:15`.

I tried getting at the submodule in various other ways, but none of them work; the `sops` attribute remains inaccessible.

I asked the same question [on the niv bug tracker](https://github.com/nmattia/niv/issues/252) as it seems like a documentation problem on their end also, but maybe you know of a quick solution?

**Comment by Mic92** [comment]
Hi. The current documentation is miss leading, it was meant as a placeholder what installation methods I want to add later. I will write it down now.
