### ISSUE TITLE
always importing rsa key when it should use ed25519 key

### ISSUE THREAD

**Issue by 06kellyjac** [Mic92/sops-nix#200]
```
activating the configuration...
setting up /etc...
sops-install-secrets: Imported /etc/ssh/ssh_host_rsa_key with fingerprint XXXXXXXXXXXXXXXXXXXXXXX
/nix/store/ym7kih9py7r2h4lfh9fiz42v5pplfzqs-sops-install-secrets-0.0.1/bin/sops-install-secrets: Failed to decrypt
```

config:

```
sops.defaultSopsFile = ./secrets/secrets.yaml;
sops.age.sshKeyPaths = [ "/etc/ssh/ssh_host_ed25519_key" ];
```

and even without that `sops.age.sshKeyPaths` config things look right in the repl:

```
nixosConfigurations.machine.config.sops.sshKeyPaths
trace: Obsolete option `sops.sshKeyPaths' is used. It was renamed to `sops.gnupg.sshKeyPaths'.
[ ]

nix-repl> nixosConfigurations.machine.config.sops.gnupg.sshKeyPaths
[ ]

nix-repl> nixosConfigurations.machine.config.sops.age.sshKeyPaths
[ "/etc/ssh/ssh_host_ed25519_key" ]
```

so I have no idea why it's reading `/etc/ssh/ssh_host_rsa_key`

looks related to https://github.com/Mic92/sops-nix/issues/65#issuecomment-1155679490

**Comment by Mic92** [comment]
reading the rsa key shouldn't cause problems though. Sops will try all available keys on the system to decrypt your secret.
Have you done `sops updatekeys` on your encrypted sops file after updating `.sops.yaml`? This should add the missing key to your sopsfile.

**Comment by Mic92** [comment]
The message you are seeing is the rsa key being imported as pgp key, your ed25519 key won't show up as an import even though it might be imported, because of https://github.com/Mic92/sops-nix/pull/118
Does it by chance work if you explicitly set: `sops.gnupg.sshKeyPaths = lib.mkForce []`?

**Comment by 06kellyjac** [comment]
I havent put the force since it already looked empty in the repl but ill give that a go.
Ill also make sure I ran sops updatekeys when I can

Thanks

**Comment by 06kellyjac** [comment]
`sops updatekeys` resolved it. :facepalm: sorry for the hassle
