### ISSUE TITLE
secret appears at /run/secrets.d/11/github_token while I expected /run/secrets.d/github_token

### ISSUE THREAD

**Issue by teto** [Mic92/sops-nix#210]
I've been using sops-nix on servers with no issue so far, it has been great. I am trying to setup my github token on unstable in the same way:
```
├───sops-nix: github:Mic92/sops-nix/2c898a6d760c0c47fecd76317175206951ab884d
│   ├───nixpkgs: github:NixOS/nixpkgs/334ec8b503c3981e37a04b817a70e8d026ea9e84
│   └───nixpkgs-22_05: github:NixOS/nixpkgs/0ad6eae04953060dff8ba28af158799c3e13878d
```

with
```
  # This will add secrets.yml to the nix store
  sops.defaultSopsFile = ../../secrets/example.yaml;

  sops.age.keyFile = "/home/teto/.config/sops/age/keys.txt";
  sops.age.generateKey = false;

  # This is the actual specification of the secrets.
  sops.secrets."github_token" = {   # <=== HERE I THEN CHANGED TO   sops.secrets.github_token
	mode = "400";
	owner = config.users.users.teto.name;
	group = config.users.users.teto.group;
  };
```
I would expect the secret to be at `/run/secrets.d/github_token` but it appears at `/run/secrets.d/10/github_token`. After a nixos-rebuild, it appeared at `/run/secrets.d/11/github_token`. Is it expected ?

**Comment by dasJ** [comment]
That's the generations dir. The stable symlinks are in /run/secrets (without the d)

**Comment by teto** [comment]
damn sorry for the noise,  I use /run/secrets everywhere and I dunno why but today I started looking at /run/secrets.d :s Thanks !
