### ISSUE TITLE
setupSecretsForUsers failed when age.keyFile not exists

### ISSUE THREAD

**Issue by c4dr01d** [Mic92/sops-nix#213]
Hi, I setup the sops-nix for my local system and cloud server, when I switching my local system config and reboot to new system, activation scripts report: "Cannot read key file: /srv/sops/keys.txt: open /srv/sops/keys.txt: No such file or directory." My local system is configured with persistence, I persisted /srv/sops, but when execute setupSecretsForUsers, the /srv/sops not mounting. :(

**Comment by Mic92** [comment]
Sorry but with the current way sops work, we cannot support this usecase. The key has to be on the root filesystem as we run sops in activation phase before any systemd services & mounts are started.
