### ISSUE TITLE
is there a way to force the install of /run/secrets ?

### ISSUE THREAD

**Issue by teto** [Mic92/sops-nix#227]
at some point I had to create /run/secrets/ssh_host_key manually to fix my ssh server and rerun a deployement.
This would fail because /run/secrets was not what sops-nix expected (a symlink  ?!). I ended up recreating the correct hierarchy like /run/secrets -> /run/secrets.d/1 with  the file /run/secrets.d/1/ssh_host_key .

I wonder if there was a builtin way to achieve this via bruteforce (e.g., backup or remove /run/secrets and let sops-nix do its thing).  Doing it by hand was annoying and it's not the first time I have to do this (because of https://github.com/Mic92/sops-nix/issues/225 mostly xD).

```
updating GRUB 2 menu...
activating the configuration...
setting up /etc...
/nix/store/x3gv1pgkcdp423cnix9qh3s9fmvb2rcz-sops-install-secrets-0.0.1/bin/sops-install-secrets: Failed to prepare new secrets directory: Cannot access /run/secrets: readlink /run/secrets: invalid argument
Activation script snippet 'setupSecrets' failed (1)
reloading user units for root...
reloading user units for nova...
setting up tmpfiles
warning: the following units failed: gitlab-runner.service

× gitlab-runner.service - Gitlab Runner
     Loaded: loaded (/etc/systemd/system/gitlab-runner.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Mon 2022-09-05 14:37:22 UTC; 31ms ago
       Docs: https://docs.gitlab.com/runner/
    Process: 4638 ExecStartPre=/nix/store/q8zzcw9162659gdj6b0iyc13gm369n4v-gitlab-runner-configure/bin/gitlab-runner-configure (code=exited, status=1/FAILURE)
         IP: 5.5K in, 1.8K out
        CPU: 327ms
```

**Comment by dasJ** [comment]
Is running `/run/current-system/activate` enough for that? It should create a new generation then iirc

**Comment by teto** [comment]
at that point in time,  I dont think sops-nix is part of /run/current-system/activate. It's an ubuntu machine I convert via nixos-infect to nixos (because the hosting doesn't let me install a nixos), the issue appears with the first deploy (done via deploy-rs). Thus /run/current-system/activate wouldn't run sops yet since the deployement fails because of my previous error.

**Comment by Mic92** [comment]
You could use `nixos-enter` from ubuntu to trigger `/run/current-system/activate` once.

**Comment by teto** [comment]
thanks for the answers. My usecase was a bit an out of the ordinary behavior so lets close this. I wll see if I get time how I can improve that behavior
