### ISSUE TITLE
Doubts about ssh-to-pgp

### ISSUE THREAD

**Issue by Ruixi-rebirth** [Mic92/sops-nix#259]
Why is the public key generated by `ssh-to-pgp -i $HOME/.ssh/id_rsa -o $USER.asc` different from what I use `gpg --armor --output public-key.txt --export root (Imported from SSH)` The exported public key is different?

**Comment by Mic92** [comment]
Could be different metadata or flags on the key: https://github.com/Mic92/ssh-to-pgp/blob/a9ed172df3fa089ba6163f258ecc1c4394c554a6/convert.go#L55

**Comment by Ruixi-rebirth** [comment]
ok, thank you
