### ISSUE TITLE
How to install using Flakes

### ISSUE THREAD

**Issue by Ulimn** [Mic92/sops-nix#280]
I've been trying to install this program using Flakes, but I haven't been able to find out how.
I never used Flakes before and sadly, I find the documentation a bit confusing. (I found plenty on how to create, but not how to use one.)

I tried to add the code snippet in the readme to my configuration.nix, but I got an error saying `The option ``inputs' does not exist`.
I assume I'm doing something completely wrong.

Can someone please help me out a little?

**Comment by Mic92** [comment]
You need to add the snippet in your `flake.nix` and not your `configuration.nix`. The configuration.nix is referenced in your flake.nix as shown in the example.
