### ISSUE TITLE
%r not being replaced when using the home-manager module

### ISSUE THREAD

**Issue by jghauser** [Mic92/sops-nix#284]
I've been using the recently introduced home-manager module and it works very nicely except for one snag. 
Say, I try to make vdirsyncer get a password from the sops file, so I add the following:
```nix
{ config, pkgs, lib, ... }:
{
  sops = {
    secrets."vdirsyncer/[redacted]" = { };
  };
  home.packages = [ pkgs.vdirsyncer ];

  xdg.configFile."vdirsyncer/config".text = ''
  ...
  password.fetch = [ "command", "${pkgs.coreutils}/bin/cat", "${config.sops.secrets."vdirsyncer/[redacted]".path}" ]
  ...
  '';
}
```

Additionally, my `home.nix` has the following snippet:
```nix
  sops = {
    age.keyFile = "/path/to/identity/file";
    defaultSopsFile = ../secrets.yaml;
  };
```

Now, if I run vdirsyncer, I get the following error:
```
Feb 26 18:48:47 tiny vdirsyncer[199212]: error: Unknown error occurred: Command '('/nix/store/gn5515zj8skk23jvrrljirgxr10fw9az-coreutils-9.1/bin/cat', '%r/secrets/vdirsyncer/[redacted]')' returned non-zero exit status 1.
```

If I tell vdirsyncer to cat the relevant file directly (`/run/user/1000/secrets/vdirsyncer/[redacted]`), things work just fine. The same problem arises for other software (e.g. borgmatic).

I'm pretty new to nixos, so this might very well be a mistake on my part! Am I missing something?

Thanks a lot for all the work on this very useful piece of software :)

**Comment by Mic92** [comment]
cc @pogobanane

**Comment by Mic92** [comment]
I don't think it's currently possible to know the uid of user in home-manager to compute this path.

**Comment by jghauser** [comment]
The path is stored in my `$XDG_RUNTIME_DIR`:
```
> echo $XDG_RUNTIME_DIR
/run/user/1000
```
Is the problem that the sops-nix service doesn't have access to this?

**Comment by Mic92** [comment]
The problem is that we don't have the actual value of $XDG_RUNTIME_DIR when the home-manager configuration is built. I think some tools might be not so happy either if they receive environment variables in their configuration.

**Comment by pogobanane** [comment]
we choose $XDG_RUNTIME_DIR as the default place to write/link secrets to. If this doesnt work for you, you can set your own absolute path as described in [1]:
`sops.secrets."[redacted]".path = "somepathwithout%r";`

[1] https://github.com/Mic92/sops-nix#use-with-home-manager

**Comment by jghauser** [comment]
Thanks @pogobanane! Is there a reason the systemd unit can't seem to use XDG_RUNTIME_DIR in my case, something I could fix? Or is it not expected to work in case of the home-manager module?

If it's the latter, then maybe the instructions could be amended. At the moment they are written as if XDG_RUNTIME_DIR should work: "And instead of decrypting to /run/secrets, the secrets are decrypted to $XDG_RUNTIME_DIR/secrets that is located on a tmpfs or similar non-persistent filesystem."

> If this doesnt work for you, you can set your own absolute path as described in [1]:
sops.secrets."[redacted]".path = "somepathwithout%r";

I figured I could do that, I just thought it would be nicer if I didn't have to define this for each secret individually.

> Can we agree on another place in $HOME as the default so that people can use `foo = "${config.sops.secrets."vdirsyncer/[redacted]".path}"` out of the box?

I think this would be a good solution!

**Comment by Mic92** [comment]
Feel free to add an option like `defaultPath = "%r/secrets";` that gets used instead of the current hardcoded path.

**Comment by pogobanane** [comment]
> Is there a reason the systemd unit can't seem to use XDG_RUNTIME_DIR in my case, something I could fix? Or is it not expected to work in case of the home-manager module?

In my understanding your `vdirsyncer/config` contains an invalid secrets path:
```
  password.fetch = [ "command", ".../bin/cat", "%r/vdirsyncer/[redacted]" ]
```
And because we dont know XDG_RUNTIME_DIR at build time, we cannot replace %r with it when creating the config file. 

If you are sure your XDG_RUNTIME_DIR always equals /run/user/1000, you can replace:
```
  password.fetch = [ "command", "${pkgs.coreutils}/bin/cat", "${config.sops.secrets."vdirsyncer/[redacted]".path}" ]
by
  password.fetch = [ "command", "${pkgs.coreutils}/bin/cat", "/run/user/1000/vdirsyncer/[redacted]"}" ]
```

**Comment by Shawn8901** [comment]
#316 which implements the suggested change for the symlink directory, which renders the home-manager sops-nix module usable as nixos module for me. I have put an example in the PR how i did set it up in my config.
