### ISSUE TITLE
Expose the values of unencrypted keys as-is

### ISSUE THREAD

**Issue by srid** [Mic92/sops-nix#317]
A subset of keys in `secrets.yaml` can be [marked as unencrypted by suffixing](https://github.com/mozilla/sops/blob/master/README.rst#48encrypting-only-parts-of-a-file) them with `_unencryprted`. This is useful for things like SSH public (not private) keys.

Can sops-nix expose these unencrypted values during evaluation? Not as `.path` (which points to `/run/...` path, accessible only during runtime), but as `.text` (accessible during evaluation time)?

I could then store public keys in secrets.yaml (along with the encrypted private keys) and use them to set options like `users.user.<name>.authorizedKeys` in a say container (that has no access to the host's `/run` directory).

**Comment by srid** [comment]
I could read `config.sops.defaultSopsFile`, run it through [fromYAML](https://github.com/purifix/purifix/blob/main/nix/build-support/purifix/from-yaml.nix) then `fromJSON` ... but it would be nice to have sops-nix provide the raw text directly.

**Comment by Mic92** [comment]
I would accept this as a contribution but won't implement it as I don't have a use-case for it.

**Comment by srid** [comment]
@Mic92 What do you think about supporting a new format, `secrets.nix`?

https://github.com/Mic92/sops-nix/blob/4f308f76633f81253a12b80e7b05b80d325005b2/pkgs/sops-install-secrets/main.go#L71-L75

Then, we won't need IFD to parse the yaml file in Nix, and can simply `import` the secrets file.

**Comment by Mic92** [comment]
sops-nix can only support formats also supported by sops. It relies on sops for editing secrets

**Comment by srid** [comment]
Closing, because I no longer need this, as I'll just use JSON as the secrets format (though, that requires #328).
