### ISSUE TITLE
Opt-in state + sops-nix?

### ISSUE THREAD

**Issue by Zaedus** [Mic92/sops-nix#335]
Because sops-nix writes to `/run` and my entire root fs is cleared (aside from some important dirs) after every reboot, I can't seem to keep these secrets on the system between reboots. I have a few ideas on how I would like to manage this problem, but none of them seem like the right approach. Is there a way to specify a different directory for secrets, such as my `/persist` directory? If not, is there a way to have them be generated on startup?

**Comment by SrEstegosaurio** [comment]
This is a _major showstopper_ for me since I do plan to implement `root-on-tmpfs` soon.

If possible, generating secrets at startup would be a good solution  but I'm also happy with being able to place them in other _(persistent)_ folders.

This just crossed my mind so it might be dumb but: why not bind mount `/run/your-secrets/...` from a persistent dir? Impermanence could handle that.

**Comment by profiluefter** [comment]
Hi, just wanted to mention that I've been running sops-nix with opt-in state for a while now and never had problems.
I have my encrypted secrets [in a repo](https://github.com/profiluefter/nixos-config/blob/09a56c8096c7cbc00b0fbd7f7c75d6451af8f267/sops.nix) and they are decrypted on each boot using my persisted ssh host key. (and the config lives in the nix store i guess which is also persisted)

**Comment by Mic92** [comment]
I don't quite yet get the use-case? How do you guys decrypt secrets? Even if everything is tmpfs except for the ssh keys, this should still work. no?

**Comment by Zaedus** [comment]
I feel like an idiot haha
I previously thought that impermanence copies the files onto the freshly booted system, meaning any changes to the secrets don't get persisted unless I copy them to my `/persist` partition every time they change. Well turns out they are mounted, not copied which makes them sync on every change. Thank you to @profiluefter for providing an example on how to do this in case someone else runs into the same problems as me.
