### ISSUE TITLE
Not sure how to use gnupgHome?

### ISSUE THREAD

**Issue by colemickens** [Mic92/sops-nix#34]
```nix
{
sops.gnupgHome = "/home/cole/.gnupg";
}
```

But it fails to decrypt during activate. I can can confirm that running `sops -d` is using PGP and decrypting successfully: Is there something I have to do to make my user's gnupghome available to it during activation?

```
sops --input-type binary --output-type binary --verbose --output ../unencrypted/wg-server.key -d wg-server.key
[PGP]	 INFO[0000] Decryption succeeded                          fingerprint=...
```

**Comment by Mic92** [comment]
I don't know if gpg likes it if `GNUPGHOME` is not owned by the same user that executes sops. GPG can be really picky here.

**Comment by Mic92** [comment]
Have you tried making root the user instead?

**Comment by colemickens** [comment]
I decided to not invest more time in trying to make gpg work, especially if it means not just re-using my existing `GNUPGHOME`. I assume you were right, I'm going to go ahead and close.
