### ISSUE TITLE
QUESTION: Why is there both nixpkgs and nixpkgs-stable in flake inputs?

### ISSUE THREAD

**Issue by Janik-Haag** [Mic92/sops-nix#353]
I noticed that sops-nix has both 
```nix
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
  inputs.nixpkgs-stable.url = "github:NixOS/nixpkgs/release-23.05";
```
in it's flake.nix, what is the reason for this? As far as I understand flakes I shuold just put something like:
```nix
    inputs.sops-nix = {
      url = "github:Mic92/sops-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
```
into my own flake.nix and if I'm running stable it's using stable and if I use unstable it uses unstable so why does sops-nix have both by default?

**Comment by Mic92** [comment]
nixpkgs-stable is just for testing the latest nixos release in our checks output. Since flake inputs are fetched lazy it's not used when you use sops-nix in your own flake inputs. If you bothered about entries in your flake.lock, you can even disable the input like this:

```
{
  inputs = {
    sops-nix.inputs.nixpkgs-stable.follows = "";
  };
}
```

**Comment by Janik-Haag** [comment]
Thanks for the quick answer!
