### ISSUE TITLE
Allow specifying multiple sops files per host

### ISSUE THREAD

**Issue by Pizmovc** [Mic92/sops-nix#378]
Hey, first of all thanks for this great project. I don't know how I would manage secrets with Nix without it.

I do have one question or suggestion. Is it possible to provide multiple sops files per host? 

I was not able to find a module option or example of this. Perhaps I just missed it?

My use case is that I'd like to have a sops file for common secrets that are not specific to any host, but are shared across the whole network. I'd like to include that one on all hosts in addition to the host specific sops file.

Usage could be something along the lines of 

```nix
config = {
  # Load the host secrets file
  sops.defaultSopsFile = ../../secrets/my-host.yaml;
  # Load some common secrets
  sops.additionalSopsFiles = [
    ../../secrets/common.yaml
  ];
}
```

or 

```nix
config = {
  # Load the secret files
  sops.sopsFiles = [
    ../../secrets/common.yaml
    ../../secrets/my-host.yaml
  ];
}
```

**Comment by Pizmovc** [comment]
I see! I missed that one. That does solve the problem, I have tried it and it works. Thanks!

I'm closing this issue, but feel free to reopen if you think this is something that would make sense to implement anyway.

**Comment by dkowis** [comment]
Sorry to resurrect the issue, but it's the exact problem I'm having right now, and maybe it's as simple as me being a NixOS Noob :tm: and not knowing the right way to do this:

```nix
  # create the sops secrets paths so I can reference them
  sops.secrets."wordpress.db.host" = {
    sopsFile = ../../secrets/wordpress.yaml;
  };
  sops.secrets."wordpress.db.user" = {
        sopsFile = ../../secrets/wordpress.yaml;
  };
  sops.secrets."wordpress.db.password" = {
        sopsFile = ../../secrets/wordpress.yaml;
  };
```

I've kinda got a mindset of "all hosts secrets" and then "per purpose" or "per host" secrets. It'd be kinda nice if I could specify once how to give that sops file once. Kinda like the usage above.

Doing it per-secret does work, but I have to repeat myself.

**Comment by Mic92** [comment]
You can use this pattern

```
let
  wordPressSecrets.sopsFile = ../../secrets/wordpress.yaml;
in
  # create the sops secrets paths so I can reference them
  sops.secrets."wordpress.db.host" = wordPressSecrets;
  sops.secrets."wordpress.db.user" = wordPressSecrets;
  
  sops.secrets."wordpress.db.password" = wordPressSecrets // {
    # here you can override the default
  };
}
```

**Comment by dkowis** [comment]
> You can use this pattern


Thanks! that worked perfectly! I'll spend more time learning Nix!
