### ISSUE TITLE
Sops-nix in Darwin

### ISSUE THREAD

**Issue by TaylorFinklea** [Mic92/sops-nix#396]
Trying to install sops-nix on Darwin and am getting the below error. What is the proper way to install sops-nix for Darwin via flakes? 

``` bash
       error: attribute 'darwinModules' missing

       at /nix/store/9shhci5aad2l7mx0gvwzgzzfpqccwp3a-source/flake.nix:38:11:

           37|
           38|           sops-nix.darwinModules.sops
             |           ^
           39|         ];
```

**Comment by kalbasit** [comment]
See https://github.com/Mic92/sops-nix/issues/163. It's currently not supported and you need to use home-manager. I was hoping to use it as well with nix-darwin but I guess HM it is.

**Comment by TaylorFinklea** [comment]
OK good to know, thank you!
