### ISSUE TITLE
Cannot decrypt secret file

### ISSUE THREAD

**Issue by yoctocell** [Mic92/sops-nix#41]
When I do `nixos-rebuild switch`, I get the following error:

```
...
setting up secrets...
/nix/store/4s57247wv7h4p77kn4isi9idgzwhsb7w-sops-install-secrets-0.0.1/bin/sops-install-secrets: Failed to decrypt '/nix/store/swrk0ywakisy6wqys1ahh80zmymwb37x-secrets.yaml': Error getting data key: 0 successful groups required, got 0
Activation script snippet 'setup-secrets' failed (1)
reloading user units for yoctocell...
setting up tmpfiles
warning: error(s) occurred while switching to the new configuration
```

I have the following in my nixos config:

```nix
{
  sops.gnupgHome = "/home/yoctocell/.gnupg";

  sops.secrets.example-key = {
    owner = "yoctocell";
    group = "yoctocell";
    sopsFile = ./secrets/secrets.yaml;
  };
}
```

Where the contents of `secrets/secrets.yaml` is:

```yaml
example-key: example-value
another-key: another-value
```

If I run `sops secrets/secrets.yaml` from the terminal, it decrypts the file and opens it in my `$EDITOR`. Is there something I am missing from the documentation?

**Comment by Mic92** [comment]
GNUPGHOME needs to be owned by root or else gpg will blow up: https://github.com/Mic92/sops-nix/issues/34#issuecomment-671705304

**Comment by yoctocell** [comment]
Isn't it unsafe to store users's gpg keys in a directory owned by root?

**Comment by Mic92** [comment]
@yoctocell It's not unsafe but gnupg won't allow .gnupg to be readable by two different users. So you will need to have a second .gnupg store for sops/root only.

**Comment by yoctocell** [comment]
@Mic92 Thanks for the clarification. I will test it with my ssh keys.
