### ISSUE TITLE
tpm2 support

### ISSUE THREAD

**Issue by lizelive** [Mic92/sops-nix#430]
I want to use host-specific key so once I trust a particular node into my repo, I can keep updating it even if i wipe it.

it [may be possible with GnuPG](https://github.com/getsops/sops/discussions/1321) but i'm not an expert.

also [systemd-creds](https://github.com/ryantm/agenix/issues/123) may be complicated solution.

**Comment by Mic92** [comment]
Same as: https://github.com/Mic92/sops-nix/issues/377
