### ISSUE TITLE
README.md: Real-world examples are outdated/contain dead links

### ISSUE THREAD

**Issue by preisi** [Mic92/sops-nix#445]
Inside the README.md, you've linked and briefly described the sops-nix setup of your personal configuration as real-world example.
However, its description appears to be out of date as your configuration seems to have deviated quite a bit from the documented method of using sops-nix: For once, it no longer has a secrets directory for each host containing secrets. Consequently, the respective link is dead. In addition, it does no longer contain a `.sops.yaml` with the respective creation_rules. (Instead, you seem to have resorted to using a 'sops' directory in your configuration repository's root containing symlinks and 'key.json' files for each host/user.)

**Comment by Mic92** [comment]
You are right. I am using this cli now: https://git.clan.lol/clan/clan-core/src/branch/main/docs/secrets-management.md
I replaced the link.
