### ISSUE TITLE
Doesn't use ssh-agent for caching passphrase

### ISSUE THREAD

**Issue by yoctocell** [Mic92/sops-nix#46]
When using ssh with a passphrase, doing `nixos-rebuild switch` results in an error:

```
setting up secrets...
/nix/store/6smf5qa87ggmcd85d7ixhw76kx13b018-sops-install-secrets-0.0.1/bin/sops-install-secrets: Error setting up gpg keyring: failed to parse private ssh key: ssh: this private key is passphrase protected
Activation script snippet 'setup-secrets' failed (1)
reloading user units for yoctocell...
setting up tmpfiles
warning: error(s) occurred while switching to the new configuration
```

This happens even when `ssh-agent` caches the passphrase, meaning that doing a `git push` wouldn't ask me for the passphrase. Is there a workaround for this, or do I have to remove the passphrase?

**Comment by Mic92** [comment]
The ssh-agent does not cache the passphrase but the decrypted private key. It however does not expose the private key but only to perform common crypto operations with it so we cannot use it to convert it to gnupg: https://github.com/Mic92/sops-nix/blob/6a921737d4685141c6388f4b8d85797033252f0a/pkgs/sops-install-secrets/main.go#L484
If you want your host ssh key to be encrypted you need an alternative ssh key for sops-nix: https://github.com/Mic92/sops-nix/blob/6a921737d4685141c6388f4b8d85797033252f0a/modules/sops/default.nix#L133

**Comment by yoctocell** [comment]
@Mic92 Thanks for taking the time and explaining! Closing this issue as by problem is now solved.
