### ISSUE TITLE
"/nix/store/... is not in the nix store"

### ISSUE THREAD

**Issue by ncfavier** [Mic92/sops-nix#48]
I'm doing something like

```nix
{
  sops.secrets.foo.sopsFile = "${secretsPath}/foo"; # where secretsPath = "/nix/store/..."
}
```

but this fails because of this check:

https://github.com/Mic92/sops-nix/blob/b0d764fccdd35588ebda2907911099198f73c89a/modules/sops/default.nix#L154

I *could* use `secretsPath + "/foo"` instead, but I feel like I shouldn't have to. Is there a better way to check whether a path is in the Nix store?

**Comment by Mic92** [comment]
One could check if it starts with `builtins.storeDir`.

```nix
nix-repl> builtins.storeDir
"/nix/store"
```

**Comment by ncfavier** [comment]
Maybe with a round-trip through `builtins.toPath` and `builtins.toString` first in order to normalise it.

**Comment by Mic92** [comment]
I don't want to force it to be a path otherwise it might be copied to the nix store without the user intending to do so.

**Comment by ncfavier** [comment]
`toString` converts a path to a string without copying anything to the store.

The manual says `toPath` is deprecated, so it would rather look like:

```nix
lib.hasPrefix builtins.nixStore (toString (/. + sopsFile))
```

**Comment by Mic92** [comment]
Ok. Do you mind open a PR for this?

**Comment by ncfavier** [comment]
Upon further investigation, the scenario I was describing can only work if `nix.useSandbox` is set to `false` (which I don't really want), because otherwise the builder for `checked-manifest.json` doesn't have access to `secretsPath`, even if it's in the store.

So I think it's actually sane to require a path if `validateSopsFile` is enabled.

The error message is a bit confusing though, maybe I'll make a PR to change that.

**Comment by Mic92** [comment]
Thanks!
