### ISSUE TITLE
[Feature?] Use from devShell flake with direnv

### ISSUE THREAD

**Issue by ppenguin** [Mic92/sops-nix#489]
Since activating secrets is "just" shell logic (called a service and/or activation script currently), it should also be possible to have `sops-nix` provide a function that generates a script that can be used in a `devShell` env?

It could set an env var like `_SOPS_SCRIPT` that, when executed, populates the secrets, and/or has additional functionality to make it sourcable and set env vars with secrets defined in the dev repo directly?

**Comment by phfroidmont** [comment]
You can do this with sops and direnv directly. You can put this in your `.envrc` for instance :
```bash
export TF_HTTP_PASSWORD=`sops -d --extract '["gitlab"]["password"]' secrets.enc.yml`
```

**Comment by Mic92** [comment]
Also feel like sops is sufficient here.

**Comment by ppenguin** [comment]
@phfroidmont  @Mic92 Thanks for the info, could have thought of that, good solution!
