### ISSUE TITLE
ssh-to-pgp: Support generating a public GPG key from a public SSH key

### ISSUE THREAD

**Issue by JJJollyjim** [Mic92/sops-nix#49]
Currently, the readme suggests doing something like:

```
ssh youruser@server01 "sudo cat /etc/ssh/ssh_host_rsa_key" | ssh-to-pgp -o server01.asc
```

Which means reading the secret material from the server.

Is it possible to produce the same PGP public key from the SSH public key string, i.e. the string `ssh-rsa [some base64] user@host`?

This feels safer, and might be easier for users to understand (I was certainly confused by this process...)

**Comment by Mic92** [comment]
No. It generates a public key but it needs the private ssh key because gnupg needs a signed public key also it would be not be required in theory. However with sops new age support it would be possible to use the public ed25519 key.

**Comment by Mic92** [comment]
Closing this as we cannot support this with gpg.
