### ISSUE TITLE
Bug: Failed to set user authorized SSH key file from secret

### ISSUE THREAD

**Issue by filipdutescu** [Mic92/sops-nix#500]
# Description

I am working on a NixOS server box which only allows a couple of users to login via SSH, by SSH key and not password. I want to setup those users' authorization files from sops secrets, as opposed to hardcoding the public keys. If any more details/code is needed, I am happy to provide them, but I will initially only present what I think are the relevant code snippets:

```nix
# users.nix (simplified to contain only 1 user)
{
  constants,
  inputs,
  config,
  ...
}: let
  authorizedKeyFile = config.sops.secrets."${constants.users.user1.secrets.authorizedKey}".path;
  allowedUser1 = constants.users.user1.username;
in {
  # ...
  users = {
    # only allow users to be created through the system configuration
    mutableUsers = false;

    users."${allowedUser1}" = {
      name = allowedUser1;
      openssh.authorizedKeys.keyFiles = [ constants ];
    };
  };

  # ...
}
```
```nix
# sops-nix.nix (simplified to contain only 1 user)
{
  constants,
  inputs,
  ...
}: let
  user1Secrets = constants.users.user1.secrets;
  usersSopsFile = ./secrets/users.yaml;
in {
  imports = [
    inputs.sops-nix.nixosModules.sops
  ];

  sops.secrets."${user1Secrets.authorizedKey}" = {
    sopsFile = usersSopsFile;
    neededForUsers = true;
  };
}
```
```nix
# constants.nix
{
  users = {
    user1 = {
      username = "myuser";

      secrets = {
        authorizedKey = "myuser/authorized_key";
      };
    };
  };
}

```

To build my test VM (to ensure all is fine prior to deployment), I run `nixos-rebuild build-vm --flake .#myserver --impure`.

# Expected behvaiour

The VM builds successfully and I go on to spend countless hours figuring out what I managed to screw up in the config and customizing the server.

# Actual behaviour

The build crashes with the following error:

```zsh
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'nixos-vm'
         whose name attribute is located at /nix/store/ch82i0ka6gw80amas17rfy392yyidpsf-source/pkgs/stdenv/generic/make-derivation.nix:348:7

       … while evaluating attribute 'buildCommand' of derivation 'nixos-vm'

         at /nix/store/ch82i0ka6gw80amas17rfy392yyidpsf-source/pkgs/build-support/trivial-builders/default.nix:87:14:

           86|       enableParallelBuilding = true;
           87|       inherit buildCommand name;
             |              ^
           88|       passAsFile = [ "buildCommand" ]

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: opening file '/run/secrets-for-users/user1/authorized_key': No such file or directory
```

# Additional details

I can provide a longer trace if needed, so please let me know if you do! I am also willing to share any relevant details.

**Comment by Mic92** [comment]
Currently authorized keys are read by NixOS at evaluation time while sops only provides them at runtime. That means sops-nix cannot be used as it cannot provide the plaintext value to nix.

**Comment by filipdutescu** [comment]
I see, thank you for the very timely reply, I very much appreciate it!

Would you happen to have, by any chance, a recommendation for how to handle my use case without sops-nix? Am I stuck with hardcoding it and leave it at that?

**Comment by Mic92** [comment]
What is the thread-model here. Can you not just store public keys without encryption?

**Comment by filipdutescu** [comment]
Actually, after looking at it some more, it should be fine to just use the public key in code, where I need it. Thanks for the clarifications!
