### ISSUE TITLE
How to have secrets accessible to multiple services?

### ISSUE THREAD

**Issue by poperigby** [Mic92/sops-nix#518]
Is it possible to make `sops-nix` secrets accessible to multiple services? I'm guessing by using groups, but I'm not quite sure how to do that, or if it's the best way.

**Comment by Mic92** [comment]
You can specify a group on a secret: https://github.com/Mic92/sops-nix/blob/83b68a0e8c94b72cdd0a6e547a14ca7eb1c03616/modules/sops/default.nix#L73

```
sops.secrets.<yoursecret>.group = "yourgroup";
```

And than add your services to an newly created group:

```
systemd.service.<yourserver>.serviceConfig.SupplementaryGroups  = [ "yourgroup" ];
users.groups.yourgroup = {};
```
