### ISSUE TITLE
Document `age` usage

### ISSUE THREAD

**Issue by jtrakk** [Mic92/sops-nix#53]
Sops [recently got `age` support](https://github.com/mozilla/sops/pull/688). Is it possible to use `age` with sops-nix?

**Comment by Mic92** [comment]
I have not tested it yet. It should be possible by using `SOPS_AGE_KEY_FILE` as described here https://github.com/mozilla/sops/pull/688/files#diff-7b3ed02bc73dc06b7db906cf97aa91dec2b2eb21f2d92bc5caa761df5bbc168fR181
This would require to also update sops here: https://github.com/Mic92/sops-nix/blob/master/go.sum

**Comment by jtrakk** [comment]
Where should I set the `SOPS_AGE_KEY_FILE` variable? If I just do it in the shell where I run `nixos-rebuild`, sops won't see it.

**Comment by Mic92** [comment]
I think we need to extend the module and set it here: https://github.com/Mic92/sops-nix/blob/797e7552776441a018e0a7299b5ba647aed40ffe/modules/sops/default.nix#L160

**Comment by jtrakk** [comment]
For reference the good rev is this PR https://github.com/mozilla/sops/pull/788 that uses the armor format. The earlier one on sops develop branch doesn't work reliably.

**Comment by Mic92** [comment]
I hope I get to implementing converting ssh ed25519 keys to sops/age keys soon similar how it was done for gpg.

**Comment by jtrakk** [comment]
Age natively supports ssh keys, but the Age feature of Sops doesn't include ssh keys.

**Comment by Mic92** [comment]
> Age natively supports ssh keys, but the Sops PR that adds Age doesn't include the ssh keys feature.

That's not an issue. In my implementation for sops-install-secrets I already do the ssh rsa to pgp key conversion. For age that could be applied in the same way.

**Comment by Mic92** [comment]
Proper age support comes here: https://github.com/Mic92/sops-nix/pull/95
