### ISSUE TITLE
sops-nix failing to switch Home Manager configuration on NixOS 23.11

### ISSUE THREAD

**Issue by flexiondotorg** [Mic92/sops-nix#535]
Since https://github.com/Mic92/sops-nix/pull/534 was merged sops-nix is failing to switch Home Manager:

```
error: lib.path.hasStorePathPrefix: Argument is of type string, but a path was expected
```

Here's the error log:

```
error:
       … while evaluating a branch condition

         at /nix/store/g861759ghxxwvyfdbv17xf3iahgm8rcb-source/lib/lists.nix:57:9:

           56|       fold' = n:
           57|         if n == len
             |         ^
           58|         then nul

       … while calling the 'length' builtin

         at /nix/store/g861759ghxxwvyfdbv17xf3iahgm8rcb-source/lib/lists.nix:55:13:

           54|     let
           55|       len = length list;
             |             ^
           56|       fold' = n:

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: lib.path.hasStorePathPrefix: Argument is of type string, but a path was expected
┏━ 1 Errors: 
┃ error:
┃        … while evaluating a branch condition
┃ 
┃          at /nix/store/g861759ghxxwvyfdbv17xf3iahgm8rcb-source/lib/lists.nix:57:9:
┃ 
┃            56|       fold' = n:
┃            57|         if n == len
┃              |         ^
┃            58|         then nul
┃ 
┃        … while calling the 'length' builtin
┃ 
┃          at /nix/store/g861759ghxxwvyfdbv17xf3iahgm8rcb-source/lib/lists.nix:55:13:
┃ 
┃            54|     let
┃            55|       len = length list;
┃              |             ^
┃            56|       fold' = n:
┃ 
┃        (stack trace truncated; use '--show-trace' to show the full trace)
┃ 
┃        error: lib.path.hasStorePathPrefix: Argument is of type string, but a path was expected
┣━━━                                                            
┗━ ∑ ⚠ Exited with 1 errors reported by nix at 11:44:05 after 0s
Error: 
   0: Command exited with status Exited(1)
```

**Comment by Mic92** [comment]
What is FTBFS?

**Comment by flexiondotorg** [comment]
I looked like FTBFS (failure to build from source) initially. I've changed the issue title.

**Comment by Mic92** [comment]
What value does your `age.keyFile` option points to?

**Comment by flexiondotorg** [comment]
> What value does your `age.keyFile` option points to?

- For NixOS: `keyFile = "/home/${username}/.config/sops/age/keys.txt";`
- For Home Manager: `"${config.home.homeDirectory}/.config/sops/age/keys.txt";`

**Comment by Mic92** [comment]
Fix here: https://github.com/Mic92/sops-nix/pull/536

**Comment by flexiondotorg** [comment]
Thank you 🙇 That fixed it :+1:

**Comment by flexiondotorg** [comment]
@Mic92 Sadly, this is not entirely fixed. The sops-nix systemd user service is failing to start.

Therefore, `/run/user/<UID>/secrets` is not being symlinked to `/run/user/1000/secrets.d/<num>`, resulting in `sops.secrets` paths in Home Manager referencing missing files.

**Comment by Mic92** [comment]
@flexiondotorg There are no more symlinks in /run/user/<uid> since https://github.com/Mic92/sops-nix/pull/530/files
Please use `config.sops.secrets.<name>.path` to access secrets.

**Comment by Mic92** [comment]
But maybe this is your actual issue? https://github.com/Mic92/sops-nix/pull/530#issuecomment-2063309938

**Comment by Mic92** [comment]
Could you check if applying this fix, is solving your problem?

**Comment by Mic92** [comment]
Also what concrete error are you getting? According to https://github.com/Mic92/sops-nix/blob/ac538092be2723b68fd4ff75eba7684480451c8f/pkgs/sops-install-secrets/main.go#L197
it should create parent directories.

**Comment by sedlund** [comment]
getting this after same PR when deploying with deploy-rs to 23.11 and unstable with home-manager -- revert to github:Mic92/sops-nix/7f49111 resolves.

```
░░ The job identifier is 921.
Apr 18 19:37:02 sgp1 4jj80vvakrghmxqhprnx0339ba0xnnwa-sops-nix-user[3205708]: sops-install-secrets: Imported /home/sedlund/.ssh/id_ed25519 as age key with fingerprint age1upwqj6xhlj0xndcuwamdpsteuv2f39qmw2meh5man5u5t9qr4fzsmzkw2s
Apr 18 19:37:02 sgp1 4jj80vvakrghmxqhprnx0339ba0xnnwa-sops-nix-user[3205708]: /nix/store/8291niqm5j7qxrb85gni1hga7x1452h1-sops-install-secrets-0.0.1/bin/sops-install-secrets: Cannot update secrets symlink: symlink /run/user/1000/secrets.d/1 /home/sedlund/.config/sops-nix/secrets: no such file or directory
```

**Comment by flexiondotorg** [comment]
> Please use `config.sops.secrets.<name>.path` to access secrets.

`sops.secrets.<name>.path` is how I access secrets via Home Manager.

**Comment by flexiondotorg** [comment]
> But maybe this is your actual issue? [#530 (comment)](https://github.com/Mic92/sops-nix/pull/530#issuecomment-2063309938)

This does appear to be the issue. Here's the patch I used to test it:

- https://github.com/flexiondotorg/sops-nix/commit/97889b4da4f45a4c1a3a3014d96aae8789f151a9

**Comment by sedlund** [comment]
that patch works for me as well

**Comment by stratosgear** [comment]
I also get errors after upgrading just now.

In my case, during `nixos-rebuild switch --flake ...` , I get a:

```
Apr 18 17:02:50 iocaine systemctl[3065687]: Job for sops-nix.service failed because the control process exited with error code.
Apr 18 17:02:50 iocaine systemctl[3065687]: See "systemctl --user status sops-nix.service" and "journalctl --user -xeu sops-nix.service" for details.
Apr 18 17:02:50 iocaine systemd[1]: home-manager-stratos.service: Main process exited, code=exited, status=1/FAILURE
Apr 18 17:02:50 iocaine systemd[1]: home-manager-stratos.service: Failed with result 'exit-code'.
Apr 18 17:02:50 iocaine systemd[1]: Failed to start Home Manager environment for stratos.
```

and journalctl --user -xeu sops-nix.service shows:

```
Apr 18 16:59:15 iocaine y01lyfskishv5mwly2vvr5inzkh33yj6-sops-nix-user[3056369]: /nix/store/bf4phxrj9zfdhxa0kcmis0m6n6ai7m80-sops-install-secrets-0.0.1/bin/sops-install-secrets: cannot update secrets symlink: symlink /run/user/1000/secrets.d/1 /home/stratos/.config/sops-nix/secrets: no such file or directory
Apr 18 16:59:15 iocaine systemd[53301]: sops-nix.service: Main process exited, code=exited, status=1/FAILURE
```

Is this related at all with this issue, or should I open a new one?

**Comment by Mic92** [comment]
This one might fix it: https://github.com/Mic92/sops-nix/pull/541

**Comment by stratosgear** [comment]
I saw that too, but I still belong to the nix "newbies" club, so it is not clear how to apply that patch... :(

Are you planning on releasing this recent batch of fixes any time soon?  I should be able to get then when I next update my flake...  I do not think it is appropriate to bother anyone here with a request for instructions on how to apply these fixes. Unless of course instructions exist somewhere that I might  have missed them! Thanks!

**Comment by Mic92** [comment]
We don't have releases but I thought about adding them so I can add sops-install-secret to nixpkgs itself.

**Comment by Mic92** [comment]
`nix flake update` should fix it.

**Comment by stratosgear** [comment]
`nix flake update` DID fix it! Thanks!
