### ISSUE TITLE
ssh-to-pgp fails to install on macOS Big Sur

### ISSUE THREAD

**Issue by antifuchs** [Mic92/sops-nix#54]
Seems the cgo linker is being unhappy, and that causes ssh-to-pgp to fail to test - breaking any shell.nix trying to use it:

```
error: --- Error --- nix-daemon
builder for '/nix/store/fqphylg3w68pmjb606p6xxg6dgwxpsy3-ssh-to-pgp-0.0.1.drv' failed with exit code 2; last 10 log lines:
  golang.org/x/crypto/ssh
  github.com/Mic92/sops-nix/pkgs/sshkeys
  github.com/Mic92/sops-nix/pkgs/ssh-to-pgp
  running tests
  # runtime/cgo
  ld: warning: passed two min versions (10.12.0, 10.12) for platform macOS. Using 10.12.
  ld: file not found: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
  clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
  FAIL       github.com/Mic92/sops-nix/pkgs/ssh-to-pgp [build failed]
  FAIL
```

I can `go get` the ssh-to-pgp binary just fine, but I suppose it would be good to be able to use it from a nix-shell too...

**Comment by Mic92** [comment]
I suppose cgo is required so that sops use native libraries. I assume this require some fixes in nixpkgs since frameworks are set there.

**Comment by Mic92** [comment]
Does adding `CoreFoundation` to buildInputs solve the issue?

**Comment by antifuchs** [comment]
I just tried it - seems like the latest rev on master does indeed build & can be added to dev shells on Big Sur. Thanks for checking in!
