### ISSUE TITLE
Simplify installation of needed utilities a lot

### ISSUE THREAD

**Issue by ebbertd** [Mic92/sops-nix#55]
Hello,
I am trying to use sops-nix and after reading through the guide and the issues I still can't get it to work because I can't manage to install the needed utilities.
Similar to what is stated in issue #50 I suggest that the installation process for the needed utilities is not only documented but also very much simplified.
I suggest to create an overlay that can be added so that users can then just add `ssh-to-pgp` and `sops-pgp-hook` to the list of packages to be installed.
Unfortunately I don't know nix well enough yet, otherwise I would create a PR.

**Comment by Mic92** [comment]
How about adding this line?

```
$(nix-build --no-out-link 'https://github.com/Mic92/sops-nix/archive/master.tar.gz' -A ssh-to-pgp)/bin/ssh-to-pgp --help
Usage of /nix/store/k3jdkarw9dvary3xabv407igapc349kc-ssh-to-pgp-0.0.1/bin/ssh-to-pgp:
  -format string
        GPG format encoding (binary|armor) (default "armor")
  -i string
        Input path. Reads by default from standard output (default "-")
  -o string
        Output path. Prints by default to standard output (default "-")
  -private-key
        Export private key instead of public key
```

does not even require to install it.

**Comment by Mic92** [comment]
Is this easier to follow? https://github.com/Mic92/sops-nix/pull/57

**Comment by Mic92** [comment]
`sops-pgp-hook` is still not easy to install. I am thinking about changing the way this part works too.

**Comment by ebbertd** [comment]
> Is this easier to follow? #57

Yes it is. Thank you very much!

**Comment by Mic92** [comment]
ssh-to-pgp will be easier to install after https://github.com/NixOS/nixpkgs/pull/111543

**Comment by Mic92** [comment]
README now has a example shell.nix that makes installation easier.
