### ISSUE TITLE
Unable to build new derivation when using flakes error: access to absolute path '/nix/store/secrets' is forbidden

### ISSUE THREAD

**Issue by Daholli** [Mic92/sops-nix#569]
`nixos-rebuild switch --flake .# --show-trace
building the system configuration...
error:
       … while calling anonymous lambda
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/lib/attrsets.nix:1571:24:
         1570|     let f = attrPath:
         1571|       zipAttrsWith (n: values:
             |                        ^
         1572|         let here = attrPath ++ [n]; in

       … while calling the 'head' builtin
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/lib/attrsets.nix:1575:11:
         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … while calling anonymous lambda
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/lib/attrsets.nix:1205:18:
         1204|         mapAttrs
         1205|           (name: value:
             |                  ^
         1206|             if isAttrs value && cond value

       … from call site
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/lib/attrsets.nix:1208:18:
         1207|             then recurse (path ++ [ name ]) value
         1208|             else f (path ++ [ name ]) value);
             |                  ^
         1209|     in

       … while calling anonymous lambda
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/lib/modules.nix:242:72:
          241|           # For definitions that have an associated option
          242|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          243|

       … while evaluating the attribute 'value'
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/lib/modules.nix:809:9:
          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       … while evaluating the option `system.build.toplevel':

       … while evaluating the attribute 'mergedValue'
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/lib/modules.nix:844:5:
          843|     # Type-check the remaining definitions, and merge them. Or throw if no definitions.
          844|     mergedValue =
             |     ^
          845|       if isDefined then

       … while evaluating a branch condition
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/lib/modules.nix:845:7:
          844|     mergedValue =
          845|       if isDefined then
             |       ^
          846|         if all (def: type.check def.value) defsFinal then type.merge loc defsFinal

       … while evaluating the attribute 'values'
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/lib/modules.nix:838:9:
          837|       in {
          838|         values = defs''';
             |         ^
          839|         inherit (defs'') highestPrio;

       … while evaluating a branch condition
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/lib/modules.nix:834:11:
          833|           # Avoid sorting if we don't have to.
          834|           if any (def: def.value._type or "" == "order") defs''.values
             |           ^
          835|           then sortProperties defs''.values

       … while calling the 'any' builtin
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/lib/modules.nix:834:14:
          833|           # Avoid sorting if we don't have to.
          834|           if any (def: def.value._type or "" == "order") defs''.values
             |              ^
          835|           then sortProperties defs''.values

       … while evaluating the attribute 'values'
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/lib/modules.nix:937:7:
          936|     in {
          937|       values = concatMap (def: if getPrio def == highestPrio then [(strip def)] else []) defs;
             |       ^
          938|       inherit highestPrio;

       … while calling the 'concatMap' builtin
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/lib/modules.nix:937:16:
          936|     in {
          937|       values = concatMap (def: if getPrio def == highestPrio then [(strip def)] else []) defs;
             |                ^
          938|       inherit highestPrio;

       … while calling the 'concatMap' builtin
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/lib/modules.nix:824:17:
          823|         # Process mkMerge and mkIf properties.
          824|         defs' = concatMap (m:
             |                 ^
          825|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while calling anonymous lambda
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/lib/modules.nix:824:28:
          823|         # Process mkMerge and mkIf properties.
          824|         defs' = concatMap (m:
             |                            ^
          825|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while calling the 'map' builtin
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/lib/modules.nix:825:11:
          824|         defs' = concatMap (m:
          825|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |           ^
          826|         ) defs;

       … while evaluating definitions from `/nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/nixos/modules/system/activation/top-level.nix':

       … from call site
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/lib/modules.nix:825:137:
          824|         defs' = concatMap (m:
          825|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          826|         ) defs;

       … while calling 'dischargeProperties'
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/lib/modules.nix:896:25:
          895|   */
          896|   dischargeProperties = def:
             |                         ^
          897|     if def._type or "" == "merge" then

       … while evaluating a branch condition
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/lib/modules.nix:897:5:
          896|   dischargeProperties = def:
          897|     if def._type or "" == "merge" then
             |     ^
          898|       concatMap dischargeProperties def.contents

       … while evaluating the attribute 'value'
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/lib/modules.nix:607:53:
          606|                 (n: value:
          607|                   [{ inherit (module) file; inherit value; }]
             |                                                     ^
          608|                 )

       … from call site
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/nixos/modules/system/activation/top-level.nix:71:12:
           70|   # Replace runtime dependencies
           71|   system = foldr ({ oldDependency, newDependency }: drv:
             |            ^
           72|       pkgs.replaceDependency { inherit oldDependency newDependency drv; }

       … while calling 'foldr'
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/lib/lists.nix:121:20:
          120|   */
          121|   foldr = op: nul: list:
             |                    ^
          122|     let

       … from call site
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/lib/lists.nix:128:8:
          127|         else op (elemAt list n) (fold' (n + 1));
          128|     in fold' 0;
             |        ^
          129|

       … while calling 'fold''
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/lib/lists.nix:124:15:
          123|       len = length list;
          124|       fold' = n:
             |               ^
          125|         if n == len

       … while calling the 'throw' builtin
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/nixos/modules/system/activation/top-level.nix:67:10:
           66|   baseSystemAssertWarn = if failedAssertions != []
           67|     then throw "\nFailed assertions:\n${concatStringsSep "\n" (map (x: "- ${x}") failedAssertions)}"
             |          ^
           68|     else showWarnings config.warnings baseSystem;

       … while calling the 'concatStringsSep' builtin
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/nixos/modules/system/activation/top-level.nix:67:41:
           66|   baseSystemAssertWarn = if failedAssertions != []
           67|     then throw "\nFailed assertions:\n${concatStringsSep "\n" (map (x: "- ${x}") failedAssertions)}"
             |                                         ^
           68|     else showWarnings config.warnings baseSystem;

       … while calling anonymous lambda
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/nixos/modules/system/activation/top-level.nix:67:69:
           66|   baseSystemAssertWarn = if failedAssertions != []
           67|     then throw "\nFailed assertions:\n${concatStringsSep "\n" (map (x: "- ${x}") failedAssertions)}"
             |                                                                     ^
           68|     else showWarnings config.warnings baseSystem;

       … from call site
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/nixos/modules/system/activation/top-level.nix:67:77:
           66|   baseSystemAssertWarn = if failedAssertions != []
           67|     then throw "\nFailed assertions:\n${concatStringsSep "\n" (map (x: "- ${x}") failedAssertions)}"
             |                                                                             ^
           68|     else showWarnings config.warnings baseSystem;

       … while calling anonymous lambda
         at /nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source/nixos/modules/system/activation/top-level.nix:64:27:
           63|
           64|   failedAssertions = map (x: x.message) (filter (x: !x.assertion) config.assertions);
             |                           ^
           65|

       … while evaluating the attribute 'message'
         at /nix/store/5cals4p1ryzfk8yb26dmk6j0rjqkyw3w-source/modules/sops/default.nix:314:11:
          313|           assertion = builtins.pathExists secret.sopsFile;
          314|           message = "Cannot find path '${secret.sopsFile}' set in sops.secrets.${lib.strings.escapeNixIdentifier name}.sopsFile";
             |           ^
          315|         } {

       error: access to absolute path '/nix/store/secrets' is forbidden in pure evaluation mode (use '--impure' to override)`
       
I was updating my system today using nixos-unstable, when I suddenly got some sops related errors. I am not sure if this is a sops error or if this originates from somewhere else.

my config can be found here:
[sops-nix config in my nixosconfig](https://github.com/Daholli/nixOsConfig/blob/main/modules/nixos/security/sops/default.nix)

**Comment by Daholli** [comment]
I had to switch my config to use `lib.snowfall.fs.get-file "secrets/secrets.yaml"` instead now I can build derivations again

**Comment by Daholli** [comment]
> @Daholli Hmm, where would you put that command/setting? I believe I experience the same issue!

If you look at the link to my sops config, you can see that i changed the way i define where my default secrets file is, but that only works if you are using snowfall-lib

**Comment by stratosgear** [comment]
Yes, I am but while before I was getting a:

```
...

       … while evaluating the option `system.build.toplevel':

       … while evaluating definitions from `/nix/store/z71lmgd0ydfnax1b13zbrls5idf1y7ak-source/nixos/modules/system/activation/top-level.nix':

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: access to absolute path '/nix/store/secrets' is forbidden in pure evaluation mode (use '--impure' to override)
```

After making a similar case I now get a:

```
...
       … while evaluating the option `system.build.toplevel':

       … while evaluating definitions from `/nix/store/z71lmgd0ydfnax1b13zbrls5idf1y7ak-source/nixos/modules/system/activation/top-level.nix':

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: access to absolute path '/secrets' is forbidden in pure evaluation mode (use '--impure' to override)

```

My sops/default.nix: https://gitlab.com/stratosgear/ultragear/-/blob/master/modules/nixos/security/sops/default.nix?ref_type=heads#L33

**Comment by stratosgear** [comment]
Basically I changed the:

`defaultSopsFile = ./. + "../../../../../secrets/${config.networking.hostName}.yaml";`

to:

`defaultSopsFile = lib.snowfall.fs.get-file  "../../../../../secrets/${config.networking.hostName}.yaml";`

For the `sopsFile` a little further below too..

**Comment by Daholli** [comment]
defaultSopsFile = ./. + "../../../../../secrets/${config.networking.hostName}.yaml";
-> 
defaultSopsFile = lib.snowfall.fs.get-file "secrets/${config.networking.hostName}.yaml";

assuming your secrets are in this folder
https://gitlab.com/stratosgear/ultragear/-/tree/master/secrets?ref_type=heads

**Comment by stratosgear** [comment]
Bummer!  After changing the `lib.snowfall.fs.get-file` to absolute paths (from relative on my first try) I am back into gettting:

```
...
       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: access to absolute path '/nix/store/secrets' is forbidden in pure evaluation mode (use '--impure' to override) 
``` 

again.

I double checked that my edits (converting to lib.snowfall.fs.get-file) were working correctly, by using an older flake.  But as soon as I update my flake with `nix flake update`, even though I use lib.snowfall.fs.get-file it still fails with the above message... :(

**Comment by stratosgear** [comment]
Saw this too: https://github.com/snowfallorg/lib/issues/98  but does not add too much on my understanding on how to fix  this!!!

**Comment by Daholli** [comment]
have you tried it with the exact thing that I sent you? 

`lib.snowfall.fs.get-file "secrets/${config.networking.hostName}.yaml";`

**Comment by stratosgear** [comment]
Yes! That's what I meant by saying that changed to file resolution to absolute, relative to the project, instead of relative I was using on my first attempt to fix!!!

So basically we are using the same method, but I get to be the unlucky one!!!

**Comment by Daholli** [comment]
do you have a branch that i can look at? maybe i can find something

**Comment by stratosgear** [comment]
Much appreciated!!!!

I pushed my current changes to:
https://gitlab.com/stratosgear/ultragear/-/tree/snowfall-get-file-error?ref_type=heads

I have no idea how you can try this out without installing my whole system, though!  I would have never been able to locally debug anybody else's config...

**Comment by Daholli** [comment]
are you using 
[get-snowfall-file](https://snowfall.org/reference/lib/#libsnowfallfsget-snowfall-file)
over
[get-file](https://snowfall.org/reference/lib/#libsnowfallfsget-file)
conciously or is that a typo? 
I would assume you use the second one

**Comment by stratosgear** [comment]
Missed my comment from above... :)

**Comment by Daholli** [comment]
I would experiment a little with the get-file, maybe hardcode one of the names? 
not sure if maybe something breaks with the name evaluation, as you said i cant really debug your config, just wanted to look at it to see if I spot anything that is different in mine, but you even have the exact same folder structures for all things involved, the only thing is that I am (at least not yet) use variables in the path to both the agefile and the snowflall.get-file.

**Comment by stratosgear** [comment]
I tried to create a file name conflict by changing the 'secrets.yaml' to 'secrets.yml', etc,  to see if the snowfall lib indeed references the file correctly, and it indeed fails with a file not found error.  So snowfall lib DOES INDEED read the correct file.

How would I hardcode the file name? You mean, use a path without the use of `lib.snowfall.fs.get-file`.  What would a value like this look like?

**Comment by Daholli** [comment]
no i meant using a secrets.yaml instead of ${hostname}.yaml, but that seems like it can be ruled out

**Comment by stratosgear** [comment]
Much appreciate you help thus far, nonetheless!

It's stupid show-stopper bugs like these that are so hard to debug on your own that you 100% depend on other people that really prevents me from suggesting nixos to  other people...  Really happy when it works correctly, but what a bummer when it falls sideways.... :(

**Comment by Daholli** [comment]
Yeah, as someone fairly new to nix some of the issues feel so annoying, but luckily most issues for me resolved themselves  super quickly because of the amazing community. I am sure you will find a solution, just wierd that we have so similar setups, but for you it fails, which feels like it goes against the very concept of nix :3.
