### ISSUE TITLE
Can we add to the current shellHook instead of dying silently?

### ISSUE THREAD

**Issue by MartinPotier** [Mic92/sops-nix#59]
https://github.com/Mic92/sops-nix/blob/a0e8ec2e2b0f4575e1b4da5713d691c80ca5d055/pkgs/sops-pgp-hook/sops-pgp-hook.bash#L28

My current shellHook is

```
  shellHook = ''
    export NIX_PATH=nixpkgs=${src.nixpkgs}
    nix build -f deployments.nix one-runner -o deploy-one-runner
    nix build -f deployments.nix canary-runner -o deploy-canary-runner
  '';
```

which is quite useful. I did not understand at first why the `SOPS_PGP_FP` env var was not automatically set. May I suggest that we concatenate the current `shellHook` with the pgpHook? I'll try to write a PR for this.

**Comment by Mic92** [comment]
Also rather than `SOPS_PGP_FP` I would now suggest `.sops.yaml` as this works better with multiple hosts

**Comment by MartinPotier** [comment]
Hey @Mic92 thanks for the pointer. Could this be somewhere in the README? I came to sops-nix being unfamiliar with sops itself, and I suspect other people would be in the same situation.

**Comment by Mic92** [comment]
> Hey @Mic92 thanks for the pointer. Could this be somewhere in the README? I came to sops-nix being unfamiliar with sops itself, and I suspect other people would be in the same situation.

Yes. That should be added. I learned that while using sops more after I created `sops-pgp-hook.bash`
