### ISSUE TITLE
cannot look up '<sops-nix/modules/sops>' 

### ISSUE THREAD

**Issue by papanito** [Mic92/sops-nix#606]
I follow the documentation but the following instruction

``` 
imports = [ <sops-nix/modules/sops> ];
``` 

Results in

```
cannot look up '<sops-nix/modules/sops>' 
```

**Comment by papanito** [comment]
Theoretically I am using flakes: https://github.com/papanito/nixos-configuration/blob/main/flake.nix

Maybe there is something wrong with my config !?

**Comment by sedlund** [comment]
remove this:

https://github.com/papanito/nixos-configuration/blob/03f6e9205a779c6d3fdc9779dcb327634c1547fa/modules/sops.nix#L5

and add `sops-nix` to line 2

**Comment by papanito** [comment]
I also tried that and I get

```
error: path '/nix/store/ikg5hfkv9v33gpjisdy2j9mrv8p6956s-source/modules/secrets/sops.yaml' does not exist
```

**Comment by sedlund** [comment]
if you've recently added the file to your repo, you'll need to `nix flake update` to get it in the store

**Comment by papanito** [comment]
Ok important is also that the path of `sops.defaultSopsFile`  is relatively pointing to the right. In my case

```
-  sops.defaultSopsFile = ./secrets/secrets.yaml;
+  sops.defaultSopsFile = ../secrets/secrets.yaml;
```
