### ISSUE TITLE
Allow secrets to be used as strings not as file

### ISSUE THREAD

**Issue by TheCataliasTNT2k** [Mic92/sops-nix#624]
I have a few secrets, which control the monitoring behaviour for my docker containers.
These containers need to have labels, but I do not want to have these labels as clear text in my git repo.

Obviously, it is not a problem, that the secrets are readable for anyone, which has access to the server, because they already could read them right now.
Sadly, sops does not provide a way, to use secrets as actual text, only as files, which does not work for docker labels.
Is there a way to get this to work?

**Comment by clementpoiret** [comment]
This would be awesome. Currently I simply use a `builtins.readFile` to get the content of the mounted secret, and build with `--impure` flag, but maybe there is a cleaner way to do?

**Comment by Mic92** [comment]
No this doesn't work because secrets cannot be used as values: https://github.com/Mic92/sops-nix?tab=readme-ov-file#using-secrets-at-evaluation-time

**Comment by TheCataliasTNT2k** [comment]
Thanks for your answer.
Sad to see this, I will need another way then. You recommend "git-agecrypt" in the linked README, but it itself is not a solution according to their own README.
I will have to look for a different approach then.

**Comment by Mic92** [comment]
I saw people using nix plugins to decrypt at eval time.

**Comment by clementpoiret** [comment]
Thanks for pointing nix-plugins! I successfully managed to have sops-nix exposing secrets for the user, and nix-plugins to access them at eval time :+1: 

Here is a minimal reproducible example:

Nix settings:
```nix
nix = {
  settings = {
    plugin-files = "${pkgs.nix-plugins}/lib/nix/plugins";
    extra-builtins-file = [ ../libs/extra-builtins.nix ];
  };
};
```

libs/extra-builtins.nix content (**be sure you have sops installed :)**):
```nix
{ exec, ... }: {
  readSops = name: exec [ "sops" "-d" name ];
}
```

Create and encrypt your secrets with `sops secrets/eval-secrets.nix`:
```nix
{
  dns = {
    desktop = "1.1.1.2";
  };
}
```

Read at eval time such as:
```nix
{ ... }:
let
  secrets = builtins.extraBuiltins.readSops ../secrets/eval-secrets.nix;
in
{
  networking.nameservers = [ secrets.dns.desktop ];
}
```

This way I can handle both a `user-secrets.yaml` to use with sops-nix in home-manager, and a `eval-secrets.nix` to use at eval time :+1: 

Hope it'll help people reading this thread!

**Comment by nsainaney** [comment]
@clementpoiret I can't get this to work. I keep getting:

```
error: attribute 'extraBuiltins' missing
```

Where do you put the following?

```
nix = {
  settings = {
    plugin-files = "${pkgs.nix-plugins}/lib/nix/plugins";
    extra-builtins-file = [ ../libs/extra-builtins.nix ];
  };
};```

I added it to my flake.nix before `nixConfigurations` and even tried the official docs:

```
nix.extraOptions = ''
  plugin-files = ${pkgs.nix-plugins}/lib/nix/plugins
'';```

and I can't get the `extraBuiltins` attribute.

Thanks

**Comment by fasheng** [comment]
@nsainaney It looks like you should rebuild system first after setup `nix-plugins` and `extra-builtins-file`, then call `extraBuiltins` in configuration in next generation.

Thanks @clementpoiret's tutorial, I've extended some code to support parse sops `yml/json/toml` file directly so that user could store secrets in the same config file with `sops-nixs`.

**extra-builtins.nix**
```nix
{ exec, ... }: rec {
  sopsFromNix = file: exec [ "sops" "-d" file ];

  # cmd is a wrapper for exec. Since exec will parse the output of
  # command as a Nix expression, cmd will escape the output in advance,
  # so that after exec parsing it later, the original output content of
  # the command can be returned
  cmd = args: exec [ "sh" "-c"
    (''printf "\"%s\"" "$('' + (builtins.concatStringsSep " " (map (x: "'" + x + "'") args)) + '' | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/\$/\\$/g')"'')
  ];
  sopsDecrypt = file: cmd [ "sops" "-d" file ];
  sopsDecryptToJSON = file: cmd [ "sops" "--output-type" "json" "-d" file ];

  # Direct parsing json/yaml/toml through sops, using cmd to implement
  sopsFromJSON = file: builtins.fromJSON (sopsDecrypt file);
  sopsFromYAML = file: builtins.fromJSON (sopsDecryptToJSON file);
  sopsFromTOML = file: builtins.fromTOML (sopsDecrypt file);

  # Direct parsing json/yaml/toml through sops, using nix eval to
  # convert the output to nix format in advance to implement
  sopsFromJSON2 = file: exec [ "sh" "-c"
    ("nix eval --expr \"builtins.fromJSON(''\$(sops --output-type json -d '" + file + "')'')\"")
  ];
  sopsFromYAML2 = file: sopsFromJSON2 file;
  sopsFromTOML2 = file: exec [ "sh" "-c"
    ("nix eval --expr \"builtins.fromTOML(''\$(sops -d '" + file + "')'')\"")
  ];
}
```

**configurations.nix**
```nix
networking.hostName = (builtins.extraBuiltins.sopsFromYAML config.sops.defaultSopsFile).host_name;
```
