### ISSUE TITLE
auto-import gpg keys

### ISSUE THREAD

**Issue by colemickens** [Mic92/sops-nix#63]
Scenario:

- I want to boot a SBC via netboot
- I want encrypted secrets at rest (and on the netboot server)
- There is a Yubikey plugged into the SBC with a configured OpenPGP app with certs/keys

So I'd like to have `sops-nix` (or something) auto-import the gpg key that corresponds to that computer (and corresponds to the key material on the yubikey).

**Comment by Mic92** [comment]
Yubikeys should be supported by setting `gnupgHome`: https://github.com/Mic92/sops-nix#use-with-gnupg-instead-of-ssh-keys
This gnupg home must be setup to use your yubikey.

**Comment by colemickens** [comment]
I guess maybe I thought sops-nix could do this for me since you already handle a case where you import ssh keys and convert them, but I guess you're trying to get away from that when sops can handle ssh keys directly.

I'll just write some other script to initialize the gnupg dir and hook that before sops-nix. No need for this to stay open here.

**Comment by Mic92** [comment]
That's not possible because yubikeys don't allow to import keys. One could add support from yubikeys but this further than I want to go with sops-nix given that gnupg already implements this.
