### ISSUE TITLE
neededForUsers option does not exist in home-manager module

### ISSUE THREAD

**Issue by 3ulalia** [Mic92/sops-nix#693]
I'm trying to configure my system using NixOS 25.05 and home-manager in my flake. I have the following minimal config:

```nix
# in configuration.nix (NixOS)
users.users.eulalia.hashedPasswordFile = config.home-manager.users.eulalia.sops.secrets."passwords/eulalia".path;
```

```nix
# in home.nix (home-manager)
sops = {
  defaultSopsFile = inputs.self.outPath + "/secrets/secrets.yaml";
  age = {
    keyFile = config.xdg.configHome + "sops/age/keys.txt";
  };
  
  secrets."passwords/eulalia".neededForUsers = true;
};
```
Attempting to rebuild into this system results in an error, claiming that neededForUsers is not defined:

```
error: The option `home-manager.users.eulalia.sops.secrets."passwords/eulalia".neededForUsers' does not exist. Definition values:
  - In `/nix/store/jbn6fi1a5ma4fn7vz44bambvc88sjcks-source/modules/home-manager/sops.nix': true
```

Since this secret sets my password, not setting the option results in a failed rebuild.

I can alternatively set that option at the NixOS level, but since the secret is defined and managed in home-manager I had hoped to be able to set the options on that level. Is this intended?

Thanks!

**Comment by tetov** [comment]
The user passwords on Linux are checked using hashes stored in /etc/shadow, I suppose there would be ways to set it in the user home directory or by the home-manager-$user.service which can write outside of home, but that would probably be unsafe as other uses hashes could be modified this way.

So yes, this is intended.

**Comment by Mic92** [comment]
Yes. This option doesn't cannot work with home-manager, since home-manager cannot modify `/etc/shadow`.
