### ISSUE TITLE
sops-pgp-hook evaluation fails in a strict shell (set -euo pipefail)

### ISSUE THREAD

**Issue by berbiche** [Mic92/sops-nix#80]
While testing things in a local repository, I discovered with `direnv` that enabling the `strict_env` option, which executes the hook with `set -euo pipefail`, would fail to evaluate the hook and exit.

I didn't have the variable below exposed so the script would exit with `$VARIABLE_NAME: unbound variable`

https://github.com/Mic92/sops-nix/blob/4a8cb2bd5051cdce7767bc0ea817aedb3896462d/pkgs/sops-pgp-hook/sops-pgp-hook.bash#L14
https://github.com/Mic92/sops-nix/blob/4a8cb2bd5051cdce7767bc0ea817aedb3896462d/pkgs/sops-pgp-hook/sops-pgp-hook.bash#L21

Changing the logic to `"${VARIABLE_NAME-}"` would prevent errors and only assign the empty string if the variable is undefined.

**Comment by Mic92** [comment]
Should it not be `"${VARIABLE_NAME:-}"` instead? Can you make a pull request?

**Comment by berbiche** [comment]
I'll open a PR tomorrow when time permits
