### ISSUE TITLE
Does not work with `users.users.<name>.passwordFile`

### ISSUE THREAD

**Issue by lovesegfault** [Mic92/sops-nix#93]
If you attempt to do something like this:
```Nix
{
  sops.secrets.root-password.sopsFile = ./root-password.yaml;
  users.users.root.passwordFile = config.sops.secrets.root-password.path;
}
```
Where `root-password.yaml` looks like this:
```Yaml
root-password: $6$rounds=65536$00000000000000$00000000000000000000000000000000000000000000000000000000000000000000000000000000000000 
```

You end up with no password on boot for the user, looking at `/etc/shadow` shows `root:!:1::::::`. If you force reactivation to occur manually after booting by running `sudo /run/current-system/bin/switch-to-configuration switch` then `/etc/shadow` is updated and contains the correct password hash.

My guess is this is due to some annoying precedence issue, is there anyway around it?

**Comment by Mic92** [comment]
The issue is that we can only decrypt files after user being created as we need those for permissions right now.
There could be a module option that allows to decrypt secrets for root just before users are created just for this edge case.

**Comment by jakeisnt** [comment]
Is there currently any workaround?

**Comment by Mic92** [comment]
`users.extraUsers.<name>.hashedPassword` might be acceptable for some users.

**Comment by nemesamade** [comment]
> The issue is that we can only decrypt files after user being created as we need those for permissions right now.
I'm not sure if this is the case. I created a workaround in my fork my by adding the sops setup scripts as dependencies to the users activation script:
`system.activationScripts.users.deps = ([ "setup-secrets" ] ++ optional cfg.age.generateKey "generate-age-key");`
And now my passwords are getting picked up into /etc/shadow fine on boot, which seems to indicate the opposite. Can someone else confirm if this fixes the problem for them (I can open a PR if necessary).

**Comment by 0x4A6F** [comment]
You may want to throw a glance at the implementation from [agenix](https://github.com/ryantm/agenix/commit/aecba55db60d55ced4ea5bc3af12cab11f2e4950).
